#!/bin/sh
#
# BEGIN COPYRIGHT BLOCK
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation version
# 2.1 of the License.
#                                                                                 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#                                                                                 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# END COPYRIGHT BLOCK

JAVA=`which java`
if [ -z "$JAVA" -o ! -x "$JAVA" ]
then
  echo "$0: The java program is not in your path, or is not executable.";
  exit 1
fi

THEME_JAR=/usr/share/java/fedora-theme-1.0.3_en.jar
#
# Launch the Console
#
java -ms8m -mx64m -cp /usr/share/java/jss3.jar:/usr/share/java/ldapjdk.jar:/usr/share/java/fedora-base-1.0.3.jar:/usr/share/java/fedora-mcc-1.0.3.jar:/usr/share/java/fedora-mcc-1.0.3_en.jar:/usr/share/java/fedora-nmclf-1.0.3.jar:/usr/share/java/fedora-nmclf-1.0.3_en.jar:$THEME_JAR -Djava.library.path=/usr/lib -Djava.util.prefs.systemRoot="$HOME/.fedora-console" -Djava.util.prefs.userRoot="$HOME/.fedora-console" com.netscape.management.client.console.Console $*
