#!/bin/sh
#
# BEGIN COPYRIGHT BLOCK
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation version
# 2.1 of the License.
#                                                                                 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#                                                                                 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# END COPYRIGHT BLOCK
#
echo ###
echo ### Remember to setup NETSCAPE_SERVER_ROOT variable
echo ###
javac -classpath "$NETSCAPE_SERVER_ROOT/java/base.jar:$NETSCAPE_SERVER_ROOT/java/ldapjdk.jar:$NETSCAPE_SERVER_ROOT/java/mcc40.jar:$NETSCAPE_SERVER_ROOT/java/mcc40_en.jar:$NETSCAPE_SERVER_ROOT/java/nmclf40.jar:$NETSCAPE_SERVER_ROOT/java/nmclf40_en.jar:$NETSCAPE_SERVER_ROOT/java/swingall.jar:$CLASSPATH" SuperMailTopologyPlugin.java
jar c0f SuperMailTopologyPlugin.jar SuperMailTopologyPlugin.class
cp SuperMailTopologyPlugin.jar SuperMailTopologyPlugin_en.jar
